	lab8_soc u0 (
		.clk_clk                        (<connected-to-clk_clk>),                        //                     clk.clk
		.curx_w0_in_port                (<connected-to-curx_w0_in_port>),                //                 curx_w0.in_port
		.curx_w0_out_port               (<connected-to-curx_w0_out_port>),               //                        .out_port
		.curx_w1_in_port                (<connected-to-curx_w1_in_port>),                //                 curx_w1.in_port
		.curx_w1_out_port               (<connected-to-curx_w1_out_port>),               //                        .out_port
		.cury_w0_in_port                (<connected-to-cury_w0_in_port>),                //                 cury_w0.in_port
		.cury_w0_out_port               (<connected-to-cury_w0_out_port>),               //                        .out_port
		.cury_w1_in_port                (<connected-to-cury_w1_in_port>),                //                 cury_w1.in_port
		.cury_w1_out_port               (<connected-to-cury_w1_out_port>),               //                        .out_port
		.hex_digits_export              (<connected-to-hex_digits_export>),              //              hex_digits.export
		.key_external_connection_export (<connected-to-key_external_connection_export>), // key_external_connection.export
		.keycode_export                 (<connected-to-keycode_export>),                 //                 keycode.export
		.leds_export                    (<connected-to-leds_export>),                    //                    leds.export
		.mag_w0_in_port                 (<connected-to-mag_w0_in_port>),                 //                  mag_w0.in_port
		.mag_w0_out_port                (<connected-to-mag_w0_out_port>),                //                        .out_port
		.mag_w1_in_port                 (<connected-to-mag_w1_in_port>),                 //                  mag_w1.in_port
		.mag_w1_out_port                (<connected-to-mag_w1_out_port>),                //                        .out_port
		.reset_reset_n                  (<connected-to-reset_reset_n>),                  //                   reset.reset_n
		.sdram_clk_clk                  (<connected-to-sdram_clk_clk>),                  //               sdram_clk.clk
		.sdram_wire_addr                (<connected-to-sdram_wire_addr>),                //              sdram_wire.addr
		.sdram_wire_ba                  (<connected-to-sdram_wire_ba>),                  //                        .ba
		.sdram_wire_cas_n               (<connected-to-sdram_wire_cas_n>),               //                        .cas_n
		.sdram_wire_cke                 (<connected-to-sdram_wire_cke>),                 //                        .cke
		.sdram_wire_cs_n                (<connected-to-sdram_wire_cs_n>),                //                        .cs_n
		.sdram_wire_dq                  (<connected-to-sdram_wire_dq>),                  //                        .dq
		.sdram_wire_dqm                 (<connected-to-sdram_wire_dqm>),                 //                        .dqm
		.sdram_wire_ras_n               (<connected-to-sdram_wire_ras_n>),               //                        .ras_n
		.sdram_wire_we_n                (<connected-to-sdram_wire_we_n>),                //                        .we_n
		.spi0_MISO                      (<connected-to-spi0_MISO>),                      //                    spi0.MISO
		.spi0_MOSI                      (<connected-to-spi0_MOSI>),                      //                        .MOSI
		.spi0_SCLK                      (<connected-to-spi0_SCLK>),                      //                        .SCLK
		.spi0_SS_n                      (<connected-to-spi0_SS_n>),                      //                        .SS_n
		.usb_gpx_export                 (<connected-to-usb_gpx_export>),                 //                 usb_gpx.export
		.usb_irq_export                 (<connected-to-usb_irq_export>),                 //                 usb_irq.export
		.usb_rst_export                 (<connected-to-usb_rst_export>),                 //                 usb_rst.export
		.signewcurx_in_port             (<connected-to-signewcurx_in_port>),             //              signewcurx.in_port
		.signewcurx_out_port            (<connected-to-signewcurx_out_port>),            //                        .out_port
		.signewcury_in_port             (<connected-to-signewcury_in_port>),             //              signewcury.in_port
		.signewcury_out_port            (<connected-to-signewcury_out_port>),            //                        .out_port
		.signewmag_in_port              (<connected-to-signewmag_in_port>),              //               signewmag.in_port
		.signewmag_out_port             (<connected-to-signewmag_out_port>)              //                        .out_port
	);

